# -*- coding: utf-8 -*-
# 豐盛工作室：中英內容。題目為原創改寫（不引用原書文字），全部採正面表述。

WEEKS = [
  {"item": {"zh": "門與歡迎地墊", "en": "Front Door and Welcome Mat"},
   "theme": {"zh": "安全感", "en": "Safety"},
   "color": "#1f4e86",
   "intro": {"zh": "打開門，替自己鋪一塊歡迎地墊。這週先養成每天寫晨間隨筆的習慣，讓創作有個安心的起點。",
             "en": "Open the door and lay down a welcome mat. This week you start the morning pages habit and give your creativity a safe place to begin."},
   "tasks": {"zh": ["寫下 3 位曾經鼓勵你創作的人，和他們說過讓你開心的話",
                    "回想 3 句曾讓你想放棄的話，替每一句寫一個支持自己的新回應",
                    "寫一句自己的創造力宣言（例如「我是有創造力的人」），每天早上念一次",
                    "寫一封短信給小時候的自己，說說你準備重新開始的事"],
             "en": ["Name three people who encouraged your creativity and the kind words they said",
                    "Recall three remarks that made you want to quit, and write a supportive new reply to each",
                    "Write your own creative affirmation (for example \"I am a creative person\") and read it each morning",
                    "Write a short note to your younger self about what you are ready to start again"]}},
  {"item": {"zh": "圓鏡", "en": "Round Mirror"},
   "theme": {"zh": "自我認同", "en": "Identity"},
   "color": "#c4542a",
   "intro": {"zh": "掛上一面圓鏡，看清楚自己真正喜歡什麼。這週練習分辨「我喜歡」和「我應該喜歡」。",
             "en": "Hang a round mirror and look at what you truly enjoy. This week you practice telling \"I like\" from \"I should like\"."},
   "tasks": {"zh": ["畫一個圓分成六塊：靈性、運動、社交、工作、娛樂、冒險，各打 1 到 10 分，替分數最低的一塊寫一個小行動",
                    "列出 10 件你真心喜歡做的小事",
                    "找出最常佔用你時間的一件事，替自己寫一條溫和的界線",
                    "替自己寫一塊名牌：「正在練習＿＿＿的人」"],
             "en": ["Draw a circle in six slices (spirit, exercise, friends, work, play, adventure), score each 1 to 10, and plan one small step for the lowest",
                    "List ten small things you genuinely love doing",
                    "Pick the thing that takes the most of your time and write one gentle boundary for it",
                    "Make yourself a nameplate: \"Someone practicing ______\""]}},
  {"item": {"zh": "大窗", "en": "Big Window"},
   "theme": {"zh": "力量", "en": "Power"},
   "color": "#e2a83c",
   "intro": {"zh": "開一扇大窗讓光照進來。羨慕和不甘心都是線索，告訴你真正想往哪裡走。",
             "en": "Open a big window and let the light in. Envy and frustration are clues that point to where you want to go."},
   "tasks": {"zh": ["憑記憶畫出小時候房間的平面圖，標出最喜歡的東西和當時的夢想",
                    "寫下 3 位你羨慕的人，各補一句：「我其實也想要＿＿＿」",
                    "把最近一件讓你不甘心的事，改寫成一個想去做的行動",
                    "記下一件本週發生的「剛剛好」"],
             "en": ["Draw the floor plan of your childhood room from memory and mark your favorite things and dreams",
                    "Name three people you envy and finish the line \"I would love to ______ too\"",
                    "Turn a recent frustration into one thing you want to go and do",
                    "Note one perfectly timed coincidence from this week"]}},
  {"item": {"zh": "清爽書櫃", "en": "Tidy Bookshelf"},
   "theme": {"zh": "誠實", "en": "Integrity"},
   "color": "#2f7a72",
   "intro": {"zh": "整理出一座清爽的書櫃，只留下真正需要的東西。這週有個特別挑戰：暫停閱讀 7 天，把注意力留給自己。",
             "en": "Set up a tidy bookshelf that holds only what you need. This week has a special challenge: seven days off reading, so your attention comes home to you."},
   "tasks": {"zh": ["本週挑戰：7 天暫停閱讀與滑社群，把空出來的時間拿來做事、散步或發呆",
                    "列出 5 個你下輩子想試的職業，挑一個本週做一件小事靠近它",
                    "整理一個抽屜或資料夾，只留下喜歡的",
                    "寫下生活中 3 個想讓它變得更好的小地方"],
             "en": ["This week's challenge: seven days without reading or social feeds; spend the time doing, walking or daydreaming",
                    "List five careers you would try in another life, and take one small step toward one of them",
                    "Clear one drawer or folder and keep only what you love",
                    "Name three small things in your life you would like to make better"]}},
  {"item": {"zh": "星空天窗", "en": "Starry Skylight"},
   "theme": {"zh": "可能性", "en": "Possibility"},
   "color": "#2a3f73",
   "intro": {"zh": "屋頂打開一扇看得見星星的天窗。這週允許自己做夢，先不急著想怎麼做到。",
             "en": "A skylight full of stars opens in the roof. This week you let yourself dream before working out how."},
   "tasks": {"zh": ["寫下 10 個悄悄想實現的願望，越大膽越好",
                    "找出 5 句常對自己說的「沒辦法」，各改寫成「我可以先＿＿＿」",
                    "寫下：如果有 5 次人生，我會怎麼過",
                    "挑一個願望，寫下今天就能做的第一步"],
             "en": ["Write ten wishes you quietly hope for, the bolder the better",
                    "Find five \"I can't\" lines you often use and rewrite each as \"I can start by ______\"",
                    "Write how you would spend five different lives",
                    "Pick one wish and write the first step you can take today"]}},
  {"item": {"zh": "植物角", "en": "Plant Corner"},
   "theme": {"zh": "豐盛", "en": "Abundance"},
   "color": "#4f7d3a",
   "intro": {"zh": "搬進一整角綠意。豐盛不一定要花大錢，這週觀察你和金錢、時間的關係，練習好好接收。",
             "en": "Bring in a corner full of green. Abundance does not need a big budget; this week you observe your relationship with money and time, and practice receiving."},
   "tasks": {"zh": ["連續幾天記下每一筆花費，只觀察、不評價",
                    "列出 5 件花小錢或不花錢、卻讓你覺得很奢侈的事，本週做其中一件",
                    "為創作買一樣喜歡的小東西",
                    "寫下 3 件本週收到的好事"],
             "en": ["Write down every purchase for a few days; observe without judging",
                    "List five cheap or free things that feel luxurious, and do one this week",
                    "Buy one small thing you love for your creative work",
                    "Note three good things you received this week"]}},
  {"item": {"zh": "唱盤與邊櫃", "en": "Record Player"},
   "theme": {"zh": "連結", "en": "Connection"},
   "color": "#8a4f2d",
   "intro": {"zh": "放上一台唱盤，讓工作室有了聲音。這週練習專心聆聽，也練習先動手、再慢慢變好。",
             "en": "A record player brings sound into the studio. This week you practice listening closely, and starting before it is perfect."},
   "tasks": {"zh": ["每天花 15 分鐘安靜坐著或散步，聽聽周圍和自己的聲音",
                    "收集 10 張讓你心動的圖片，做成一張拼貼",
                    "寫下：如果不用做到完美，我今天會開始什麼？然後動手 15 分鐘",
                    "從頭到尾聽完一張專輯"],
             "en": ["Spend 15 quiet minutes a day sitting or walking, listening to the world and to yourself",
                    "Collect ten images that move you and make a collage",
                    "Write: if it did not have to be perfect, what would I start today? Then work on it for 15 minutes",
                    "Listen to one whole album from start to finish"]}},
  {"item": {"zh": "工作桌", "en": "Worktable"},
   "theme": {"zh": "韌性", "en": "Strength"},
   "color": "#b0422f",
   "intro": {"zh": "擺上一張穩穩的工作桌。不管幾歲，現在開始都剛剛好。",
             "en": "Set down a solid worktable. Whatever your age, now is a fine time to begin."},
   "tasks": {"zh": ["算算看：現在開始的話，幾年後能完成？到那時你一樣是那個年紀，所以就從今天開始",
                    "把一個大夢想拆成今天下午 20 分鐘就能做的一小步",
                    "寫下一次創作低潮，以及它留給你的收穫",
                    "替自己訂一個每週固定的創作時段"],
             "en": ["Do the math: if you start now, when would you finish? You will be that age anyway, so start today",
                    "Break a big dream into a step you can do in 20 minutes this afternoon",
                    "Write about a creative low point and what it gave you",
                    "Set a fixed weekly time for creative work"]}},
  {"item": {"zh": "扶手椅與毯子", "en": "Armchair and Throw"},
   "theme": {"zh": "同理", "en": "Compassion"},
   "color": "#2e6f9e",
   "intro": {"zh": "放一張柔軟的扶手椅。這週對自己溫柔一點，休息也是創作的一部分。",
             "en": "Add a soft armchair. Be gentle with yourself this week; rest is part of making things."},
   "tasks": {"zh": ["用溫柔大人的口吻，寫一封信給想創作、又有點緊張的自己",
                    "閉上眼睛想像作品完成那天的畫面、聲音和心情，再寫下來",
                    "安排一段完全不工作的休息時間",
                    "做出一件作品的 15 分鐘版本"],
             "en": ["Write a letter, in the voice of a kind adult, to the part of you that wants to create and feels a little nervous",
                    "Close your eyes, picture the day your work is finished, then write down the sights, sounds and feelings",
                    "Schedule a block of time with no work at all",
                    "Make a 15-minute version of one piece"]}},
  {"item": {"zh": "地毯", "en": "Area Rug"},
   "theme": {"zh": "守護", "en": "Self-Protection"},
   "color": "#a8452a",
   "intro": {"zh": "鋪一塊地毯，畫出屬於你的創作領域。這週替自己的時間和能量做好守護。",
             "en": "Lay down a rug that marks out your creative space. This week you look after your time and energy."},
   "tasks": {"zh": ["列出你最常拿來轉移注意力的習慣（追劇、購物、加班），挑一個本週減少",
                    "寫下 5 個讓創作卡住的地方，各配一個解法",
                    "選一段固定時間，關掉所有通知",
                    "寫下 3 件讓你充電的事，排進下週行事曆"],
             "en": ["List the habits you reach for instead of creating (bingeing, shopping, overtime) and cut one back this week",
                    "Name five things that hold up your creative work and a fix for each",
                    "Choose a fixed time slot and turn off every notification",
                    "List three things that recharge you and put them in next week's calendar"]}},
  {"item": {"zh": "靈感小架", "en": "Inspiration Shelf"},
   "theme": {"zh": "自主", "en": "Autonomy"},
   "color": "#c98a1e",
   "intro": {"zh": "釘一層小架，擺上給你力量的東西。這週相信自己的節奏。",
             "en": "Put up a small shelf for the things that give you strength. This week you trust your own rhythm."},
   "tasks": {"zh": ["在房間一角布置靈感小架，放上石頭、照片、羽毛或任何讓你心動的東西",
                    "本週做一次會流汗的運動",
                    "寫下你的創作者守則 5 條",
                    "把一件小作品分享給一個人"],
             "en": ["Arrange an inspiration shelf in a corner with stones, photos, feathers or anything that delights you",
                    "Do one workout that makes you sweat this week",
                    "Write five rules for yourself as a maker",
                    "Share one small piece with one person"]}},
  {"item": {"zh": "中央吊燈", "en": "Pendant Light"},
   "theme": {"zh": "信念", "en": "Faith"},
   "color": "#d9932b",
   "intro": {"zh": "點亮工作室中央的吊燈。專心享受動手的過程，把結果交給時間。",
             "en": "Switch on the pendant light in the middle of the studio. Enjoy the making and leave the outcome to time."},
   "tasks": {"zh": ["寫下一個想做的計畫，加上一句：「我負責動手做，結果交給時間。」",
                    "列出這 12 週遇到的 3 個美好巧合和收到的禮物",
                    "寫下下一個 12 週想完成的作品",
                    "寫一封謝謝信給 12 週前的自己"],
             "en": ["Write down a project you want to make and add: \"My job is to do the work; time takes care of the outcome.\"",
                    "List three happy coincidences and gifts from these 12 weeks",
                    "Write the piece you want to finish in the next 12 weeks",
                    "Write a thank-you note to yourself from 12 weeks ago"]}},
]

DATES = {
 "zh": ["去一間沒去過的文具店慢慢逛", "搭公車坐到沒去過的站，下車散步", "到二手書店找封面最好看的一本書",
        "去植物園認識三種新植物", "一個人看一部清單外的電影", "逛傳統市場，拍 5 張顏色漂亮的照片",
        "在美術館只看一件作品，看 15 分鐘", "逛一間唱片行或樂器行", "買一樣從沒吃過的零食",
        "找一家有大窗的咖啡店，畫下窗外風景", "在家煮一道從沒做過的菜", "去五金行找 3 樣有趣的小東西",
        "日落前去河堤或海邊走走", "去手作材料店摸摸各種布料", "早起看一次日出",
        "去老街抬頭看屋頂的裝飾", "逛夜市，挑一樣東西慢慢吃", "在圖書館隨手拿一本雜誌讀完",
        "重溫一樣你小時候最喜歡的東西", "走一條平常不走的路回家", "去花市買一枝花放在桌上",
        "坐在公園長椅上聽 15 分鐘的聲音", "逛玩具店，挑一個想送給小時候自己的玩具", "去看一場免費的展覽或表演"],
 "en": ["Browse a stationery shop you've never visited", "Ride a bus to a new stop and wander", "Find the book with the loveliest cover in a used bookstore",
        "Learn three new plants at a botanical garden", "See a film that isn't on your list, on your own", "Walk a market and photograph five beautiful colors",
        "Spend 15 minutes with one artwork in a museum", "Browse a record shop or music store", "Try a snack you've never had",
        "Sketch the view from a café with big windows", "Cook a dish you've never made", "Find three fun little objects in a hardware store",
        "Walk by a river or the sea before sunset", "Touch every fabric in a craft store", "Get up early for a sunrise",
        "Look up at the rooftops on an old street", "Pick one thing at a night market and eat it slowly", "Read a random magazine cover to cover at the library",
        "Revisit something you loved as a child", "Take a new route home", "Buy a single flower for your desk",
        "Sit on a park bench and listen for 15 minutes", "Pick a toy you'd give your younger self", "Go to a free exhibition or show"],
}

AFFIRM = {
 "zh": ["我是有創造力的人。", "今天寫下的每個字都算數。", "我可以慢慢來。", "好點子正在路上。",
        "我值得花時間在喜歡的事上。", "試錯是作品的一部分。", "我的感受值得被寫下來。", "今天出現就很好。"],
 "en": ["I am a creative person.", "Every word I write today counts.", "I can take my time.", "Good ideas are on their way.",
        "I deserve time for what I love.", "Trying things is part of the work.", "My feelings are worth writing down.", "Showing up today is enough."],
}

FAQ = {
 "zh": [
  ("這是 The Artist's Way 的官方遊戲嗎？", "不是。這是編織日和參考書中的核心練習（晨間隨筆、藝術家約會、獨自散步、每週章節與練習）和 12 週架構設計的練習遊戲，與作者、出版社沒有關係。每週題目都由我們改寫，想完整了解請閱讀原書。"),
  ("我寫的晨間隨筆會被存起來嗎？", "不會。你打的字只留在這個分頁，完成後就清掉，不上傳、不存進瀏覽器，也不會送進流量分析。本頁只記住你哪幾天完成、勾了哪些練習，資料存在你自己的瀏覽器裡。"),
  ("一定要在網頁上打字嗎？", "不用，手寫最好。準備一本筆記本，寫滿三頁後按「我在紙上寫完了」就完成今天。網頁打字是外出或沒帶本子時的備案。"),
  ("每週的練習都要做完嗎？", "不用。每週有 4 個練習，挑有共鳴的做就好；原書也建議每週從清單裡挑幾項來做。"),
  ("可以一個週末做完 12 週嗎？", "每搬進一件新東西，下一件要 7 天後才會送到。慢慢來，是這個練習的一部分。"),
  ("隔了幾天沒寫怎麼辦？", "隨時回來繼續，進度都在。靈感芽會等你，再寫幾天它就會長出新葉子。"),
  ("換手機或清除瀏覽器資料會怎樣？", "進度存在目前這個瀏覽器，換裝置或清除網站資料就會從頭開始。"),
 ],
 "en": [
  ("Is this an official The Artist's Way game?", "No. Knitting Hiyori built this practice game around the book's core habits (morning pages, artist dates, solo walks, weekly chapters and tasks) and its 12-week structure. It is not affiliated with the author or publisher. The weekly prompts are our own; read the book for the full program."),
  ("Is my morning writing saved anywhere?", "No. What you type stays in this tab and is cleared when you finish. It is never uploaded, never stored in your browser and never sent to analytics. The page only remembers which days you finished and which practices you checked, in your own browser."),
  ("Do I have to type here?", "No, longhand is best. Keep a notebook, fill three pages, then tap \"I wrote on paper\" to finish the day. Typing here is a backup for days without your notebook."),
  ("Do I have to do every weekly task?", "No. Each week has four tasks; do the ones that speak to you. The book also suggests choosing several from each week's list."),
  ("Can I finish all 12 weeks in a weekend?", "Each new piece arrives 7 days after the last one. Taking it slowly is part of the practice."),
  ("What if I miss a few days?", "Come back whenever you like; your progress is waiting. Your sprout waits too, and grows new leaves after a few days of writing."),
  ("What happens if I switch phones or clear my browser?", "Progress lives in this browser, so a new device or cleared site data starts from the beginning."),
 ],
}

T = {
 "zh": {
  "lang": "zh-Hant-TW", "page_lang": "zh-Hant",
  "title_tag": "豐盛工作室｜The Artist's Way 12 週創造力練習遊戲｜編織日和",
  "desc": "把 The Artist's Way 的晨間隨筆、藝術家約會、獨自散步與 12 週主題做成布置遊戲：每天寫三頁，每週為工作室搬進一件新東西，12 週後住進一間豐盛的工作室。中英雙語、免費、寫的內容不上傳。",
  "page_title": "筆記|藝術家之路|豐盛工作室",
  "brand_site": "學習筆記",
  "eyebrow": "藝術家之路・12 週練習",
  "h1": "豐盛工作室",
  "lede": "一間空著的工作室，正在等你一件一件搬進喜歡的東西。每天早上寫三頁，每週帶自己出門約會一次，12 週後，這裡會是一間滿滿都是你的工作室。",
  "credit": "概念參考 Julia Cameron《創作之路：通往更高創造力的靈性道路》（The Artist's Way，舊譯《創作，是心靈療癒的旅程》）的晨間隨筆、藝術家約會、獨自散步與 12 週架構；題目由編織日和改寫，與作者及出版社無關。",
  "cta_start": "搬進工作室", "cta_continue": "繼續今天的練習",
  "stat_week": "週次", "stat_streak": "連續天數", "stat_pages": "隨筆天數", "stat_items": "已搬進",
  "nav": ["今天", "本週", "12 件", "說明"],
  "today_no": "今天", "today_h": "晨間隨筆",
  "today_p": "起床後先拿出筆記本，手寫三頁，想到什麼寫什麼，不修改、不重讀。把腦中的雜訊倒出來，位置就留給新點子。",
  "ph": "沒帶本子時，也可以在這裡寫。想到什麼寫什麼，卡住就寫「接下來我想寫……」。",
  "privacy": "你打的字只在這個分頁裡，完成後就清掉，不上傳也不保存。",
  "count_unit": "字",
  "btn_paper": "我在紙上寫完了", "btn_done": "寫滿三頁，收進抽屜", "btn_short": "今天先寫到這裡",
  "sprout": "靈感芽", "sprout_p": "最近 7 天每寫一天，就多長一片葉子；7 片會開花。",
  "start_note": "按下「搬進工作室」後，第 1 週從今天開始。",
  "week_no": "本週",
  "p_date": "藝術家約會", "p_date_d": "每週一次，留 2 到 3 小時給自己，一個人去做好玩、不為產出的事。",
  "p_walk": "獨自散步", "p_walk_d": "每週至少一次，走 20 分鐘以上，不戴耳機，讓想法自己冒出來。",
  "p_read": "閱讀本週章節", "p_read_d": "讀原書對應這週的章節：Week {n}。",
  "p_tasks": "本週練習", "p_tasks_d": "挑有共鳴的做就好，不必全部完成。",
  "btn_draw": "抽一張約會卡", "btn_redraw": "換一張", "btn_date_done": "約會完成",
  "btn_walk": "散步完成", "btn_read": "讀完了",
  "map_no": "12 件", "map_h": "12 週，12 件新東西",
  "map_p": "每週搬進一件，下一件 7 天後送到。",
  "about_no": "說明", "about_h": "怎麼玩",
  "about": ["每天：手寫三頁晨間隨筆（沒帶本子時可以在網頁上打字）。靈感芽會跟著長葉子。",
            "每週：一次藝術家約會、一次獨自散步、讀原書這週的章節，再從 4 個練習裡挑有共鳴的做。",
            "滿 7 天：按「搬進」，工作室多一件新東西，下一週的主題打開。",
            "12 週後：工作室滿滿都是你的東西，中央的吊燈亮起來。"],
  "care": "這是創作習慣練習。如果你正經歷很重的情緒，找信任的人或專業人員聊聊，會很有幫助。",
  "faq_h": "常見問題",
  "invite_h": "邀朋友一起布置",
  "invite_p": "把連結傳給朋友，各自布置自己的工作室，每週互相問一句：「這週約會去了哪裡？」",
  "btn_share": "傳給朋友", "btn_reset": "重新開始",
  "reset_q": "確定清除全部進度？清除後無法復原。", "reset_yes": "清除", "reset_no": "保留",
  "lang_link": "EN", "lang_href_rel": "/en/artists-way/abundant-studio/",
  "legal": "本站使用 Cookie 進行流量分析（Google Analytics）與顯示廣告（Google AdSense），部分連結為聯盟連結。",
  "privacy_link": "隱私權政策",
 },
 "en": {
  "lang": "en", "page_lang": "en",
  "title_tag": "The Abundant Studio | A 12-Week The Artist's Way Practice Game | Knitting Hiyori",
  "desc": "Morning pages, artist dates, solo walks and the 12 weekly themes of The Artist's Way, turned into a decorating game. Write three pages a day, bring one new piece into your studio each week, and move into an abundant studio after 12 weeks. Free; nothing you write is uploaded.",
  "page_title": "筆記|藝術家之路|豐盛工作室",
  "brand_site": "Study Notes",
  "eyebrow": "The Artist's Way · 12-week practice",
  "h1": "The Abundant Studio",
  "lede": "An empty studio is waiting for you to fill it, one loved piece at a time. Write three pages every morning, take yourself on one date a week, and in 12 weeks this will be a studio full of you.",
  "credit": "Inspired by the morning pages, artist dates, solo walks and 12-week structure of Julia Cameron's The Artist's Way. Prompts by Knitting Hiyori; not affiliated with the author or publisher.",
  "cta_start": "Move into the studio", "cta_continue": "Continue today's practice",
  "stat_week": "Week", "stat_streak": "Streak", "stat_pages": "Page days", "stat_items": "Pieces",
  "nav": ["Today", "Week", "12 pieces", "Guide"],
  "today_no": "Today", "today_h": "Morning Pages",
  "today_p": "Before anything else, open a notebook and write three pages by hand. Anything goes; don't edit, don't reread. Pour out the noise and make room for new ideas.",
  "ph": "No notebook today? Write here instead. Anything goes; if you get stuck, write \"What I want to write next is...\"",
  "privacy": "What you type stays in this tab and is cleared when you finish. Nothing is uploaded or saved.",
  "count_unit": "words",
  "btn_paper": "I wrote on paper", "btn_done": "Three pages, into the drawer", "btn_short": "That's enough for today",
  "sprout": "Sprout", "sprout_p": "Every day you write in the last 7 adds a leaf; seven leaves and it blooms.",
  "start_note": "Week 1 begins today when you move in.",
  "week_no": "This week",
  "p_date": "Artist Date", "p_date_d": "Once a week, set aside 2 to 3 hours and go alone to do something playful, with nothing to produce.",
  "p_walk": "Solo Walk", "p_walk_d": "At least once a week, walk for 20 minutes or more with no headphones and let your thoughts drift.",
  "p_read": "This Week's Chapter", "p_read_d": "Read the book's chapter for Week {n}.",
  "p_tasks": "This Week's Tasks", "p_tasks_d": "Do the ones that speak to you; there is no need to finish them all.",
  "btn_draw": "Draw a date card", "btn_redraw": "Draw another", "btn_date_done": "Date done",
  "btn_walk": "Walk done", "btn_read": "Chapter read",
  "map_no": "12 pieces", "map_h": "12 weeks, 12 new pieces",
  "map_p": "One new piece each week; the next arrives 7 days later.",
  "about_no": "Guide", "about_h": "How to play",
  "about": ["Daily: write three morning pages by hand (or type here when you have no notebook). Your sprout grows along with you.",
            "Weekly: one artist date, one solo walk, the book's chapter for the week, and whichever of the four tasks speak to you.",
            "After 7 days: tap \"Bring in\" to add a new piece to the studio and open the next theme.",
            "After 12 weeks: the studio is full of your things and the pendant light comes on."],
  "care": "This is a creative habit practice. If you are carrying something heavy, talking with someone you trust or a professional can really help.",
  "faq_h": "FAQ",
  "invite_h": "Decorate with a friend",
  "invite_p": "Send a friend the link. Each of you furnishes your own studio, and once a week you ask: where did your date take you?",
  "btn_share": "Send to a friend", "btn_reset": "Start over",
  "reset_q": "Clear all progress? This can't be undone.", "reset_yes": "Clear", "reset_no": "Keep",
  "lang_link": "中文", "lang_href_rel": "/artists-way/abundant-studio/",
  "legal": "This site uses cookies for analytics (Google Analytics) and ads (Google AdSense), and some links are affiliate links.",
  "privacy_link": "Privacy",
 },
}

UI = {
 "zh": {"week_of": "{n}／12", "items_of": "{n}／12",
        "done_typed": "今天的三頁收進抽屜了，明天早上見。", "done_paper": "紙本三頁完成，今天的晨間隨筆打勾。",
        "done_short": "今天也寫了，明天再多寫一點。",
        "bring": "搬進「{item}」", "bring_wait": "「{item}」{d} 天後送到，先把這週的練習做起來",
        "arrived": "已搬進", "next": "這週搬進", "later": "之後送到",
        "finale": "12 件都搬進來了。中央的吊燈亮著，這是一間滿滿都是你的工作室。",
        "copied": "已複製連結，貼給朋友吧", "share_text": "我在布置一間豐盛工作室：12 週，每天寫三頁。要一起嗎？",
        "date_ok": "本週約會完成", "walk_ok": "本週散步完成", "read_ok": "本週章節讀完了",
        "not_started": "按「搬進工作室」開始第 1 週",
        "leaves": "{n}／7 片葉子", "week_label": "Week {n}"},
 "en": {"week_of": "{n}/12", "items_of": "{n}/12",
        "done_typed": "Today's three pages are in the drawer. See you tomorrow morning.", "done_paper": "Three paper pages done. Today's morning pages are checked off.",
        "done_short": "You wrote today. A little more tomorrow.",
        "bring": "Bring in the {item}", "bring_wait": "The {item} arrives in {d} days; enjoy this week's practices meanwhile",
        "arrived": "Arrived", "next": "This week", "later": "Coming",
        "finale": "All twelve pieces are in. The pendant light is on, and the studio is full of you.",
        "copied": "Link copied; paste it to a friend", "share_text": "I'm furnishing an abundant studio: 12 weeks, three pages a day. Want to join?",
        "date_ok": "This week's date is done", "walk_ok": "This week's walk is done", "read_ok": "This week's chapter is read",
        "not_started": "Tap \"Move into the studio\" to start week 1",
        "leaves": "{n}/7 leaves", "week_label": "Week {n}"},
}


# 聯盟連結（蝦皮，只放中文頁）。所有聯盟網址集中在這裡，頁面由 build.py 產生。
AFF = {
 "artists_way": {"url": "https://s.shopee.tw/AKbDycrux1",
                 "title": "創作之路：通往更高創造力的靈性道路",
                 "en": "The Artist's Way: A Spiritual Path to Higher Creativity",
                 "author": "茱莉亞・卡麥隆（Julia Cameron）",
                 "note": "這個遊戲的原書。12 週的章節、練習與晨間隨筆都出自這本，舊譯本書名是《創作，是心靈療癒的旅程》。",
                 "color": "#1f4e86"},
 "creative_act": {"url": "https://s.shopee.tw/4qGHQMqR7f",
                  "title": "創造力的修行：打開一切可能",
                  "en": "The Creative Act: A Way of Being",
                  "author": "里克・魯賓（Rick Rubin）",
                  "note": "傳奇音樂製作人寫給每個人的創作筆記，篇幅短、可以隨手翻，很適合放在晨間隨筆旁邊。",
                  "color": "#c4542a"},
}
AFF_TXT = {
 "read_link": "還沒有書？在蝦皮看《創作之路》",
 "shelf_h": "書架上的兩本書",
 "shelf_p": "12 週的路上，這兩本書可以陪你走。",
 "go": "在蝦皮查看",
 "disclosure": "以上為蝦皮聯盟連結：透過連結購買，編織日和會獲得小額回饋，你付的價格不會變高；推薦內容由我們自行挑選，與作者及出版社無合作關係。",
}
